spring:
  application:
    name: EventClean

  datasource:
    url: jdbc:postgresql://localhost:5431/EventClean
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update

  flyway:
    enabled: true